# Generated by Django 5.1.5 on 2025-02-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_estrenos_fecha_pelicula_estrenos_nuevo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartelera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='estrenos',
            name='fecha_pelicula',
        ),
        migrations.AddField(
            model_name='estrenos',
            name='fecha_peliculas',
            field=models.DateField(blank=True, null=True),
        ),
    ]
