# Generated by Django 5.1.5 on 2025-02-17 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_cartelera_remove_estrenos_fecha_pelicula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('nuevo', models.BooleanField()),
                ('fecha_peliculas', models.DateField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='peliculas_imagenes/')),
            ],
        ),
        migrations.DeleteModel(
            name='estrenos',
        ),
        migrations.RemoveField(
            model_name='cartelera',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='cartelera',
            name='stock',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='cartelera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.cartelera'),
        ),
    ]
