# Generated by Django 5.1.5 on 2025-02-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_peliculas_delete_estrenos_remove_cartelera_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='peliculas_imagenes/'),
        ),
    ]
